
spring:
  datasource:
    username: 'postgres'
    url: 'jdbc:postgresql://localhost:5432/moneysense'
    password: 'Jhtcn200516'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
jwt:
    secret: 2A472D4B6150645367556B58703273357638792F423F4528482B4D6251655468
    expiration: 86400000
